// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIVenditaLibri.DataSource;

#nullable disable

namespace WebApiProvaFaseA.Migrations
{
    [DbContext(typeof(ProvaContext))]
    [Migration("20231026080126_prova3")]
    partial class prova3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiProvaFaseA.Entities.Carrello", b =>
                {
                    b.Property<int>("IdentificativoCarrello")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificativoCarrello"));

                    b.Property<int>("IdentificativoCliente1")
                        .HasColumnType("int");

                    b.Property<double>("Prezzo")
                        .HasColumnType("float");

                    b.Property<int>("ProdottoIdentificativoProdotto")
                        .HasColumnType("int");

                    b.Property<int>("Quantità")
                        .HasColumnType("int");

                    b.HasKey("IdentificativoCarrello");

                    b.HasIndex("IdentificativoCliente1");

                    b.HasIndex("ProdottoIdentificativoProdotto");

                    b.ToTable("Carrelli");
                });

            modelBuilder.Entity("WebApiProvaFaseA.Entities.Cliente", b =>
                {
                    b.Property<int>("IdentificativoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificativoCliente"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDiNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentificativoCliente");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("WebApiProvaFaseA.Entities.Prodotto", b =>
                {
                    b.Property<int>("IdentificativoProdotto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificativoProdotto"));

                    b.Property<int>("Giacenza")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prezzo")
                        .HasColumnType("float");

                    b.HasKey("IdentificativoProdotto");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("WebApiProvaFaseA.Entities.Carrello", b =>
                {
                    b.HasOne("WebApiProvaFaseA.Entities.Cliente", "IdentificativoCliente")
                        .WithMany()
                        .HasForeignKey("IdentificativoCliente1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiProvaFaseA.Entities.Prodotto", null)
                        .WithMany("Carrelli")
                        .HasForeignKey("ProdottoIdentificativoProdotto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentificativoCliente");
                });

            modelBuilder.Entity("WebApiProvaFaseA.Entities.Prodotto", b =>
                {
                    b.Navigation("Carrelli");
                });
#pragma warning restore 612, 618
        }
    }
}
